spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_URL:localhost}:3306/${DB_NAME:younme}?useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true&tinyInt1isBit=false&rewriteBatchedStatements=true
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:1234}

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: validate
    properties.hibernate:
      format_sql: true
      show_sql: ${SHOW_SQL:true}
      jdbc:
        batch_size: 200
    open-in-view: false

easy-jwt:
  access-exp: ${ACCESS_EXP:81400}
  refresh-exp: ${REFRESH_EXP:0}
  secret: ${JWT_SECRET}

ngrok:
  enabled: true
  auth-token: ${NGROK_AUTH_TOKEN}
  command: http 8080 --domain redfish-driving-exactly.ngrok-free.app

cloud:
  aws:
    credentials:
      access-key: ${ACCESS_KEY}
      secret-key: ${SECRET_KEY}
    s3:
      bucket: ${BUCKET}
    region:
      static: ap-northeast-2
    stack:
      auto: false

logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error